export const SET_SIGNUP_EMAIL = "SET_SIGNUP_EMAIL";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const SET_HAS_EDUCATION = "SET_HAS_EDUCATION";
export const SET_HAS_SUBJECT = "SET_HAS_SUBJECT";
export const SET_HAS_MEDIA = "SET_HAS_MEDIA";
