export const NotificationTypes = {
  BOOKING_ADDED: 1,
  BOOKING_INVITATION: 2,
  BOOKING_ACCEPTED: 3,
  BOOKING_REJECTED: 4,
  BOOKING_CANCELLED_TUTOR: 5,
  BOOKING_CANCELLED_STUDENT: 6,
  PAYMENT_SUCCESSFUL: 7,
  PAYMENT_FAILED: 8,
  ASSIGNMENT_ADDED: 9,
  SUBMISSION_ADDED: 10,
  NOTIFY_BOOKING_STUDENT: 11,
  NOTIFY_BOOKING_TUTOR: 12,
  PROFILE_APPROVED: 13,
  PROFILE_REJECTED: 14,
  MESSAGE_NOTIFICATION: 15,
  INACTIVE: 16
};
